/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/embeddings/projection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 3D item embedding projection
         * @description Return item coordinates for the galaxy.
         *
         *     Args:
         *         method: ``umap`` (structure-preserving, approximate for new points) or
         *             ``pca`` (linear, so a user vector projects in exactly).
         *         max_items: Point budget. The scene stops being *readable* before it
         *             stops being fast, so this is a legibility limit as much as a
         *             performance one.
         *         vertical: Restrict to one vertical.
         *         preset: Dataset preset.
         */
        get: operations["projection_api_v1_embeddings_projection_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/embeddings/projection/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Projection manifest
         * @description Describe the available projections and their limitations.
         *
         *     Served separately so the UI can label which method is active and, for
         *     UMAP, state plainly that the user star is a similarity-weighted barycentre
         *     rather than an exact projection.
         */
        get: operations["projection_meta_api_v1_embeddings_projection_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/embeddings/user/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Place one user in the projection
         * @description Return where a user sits among the projected items.
         *
         *     Two genuinely different placements, and the response says which one it
         *     gave:
         *
         *     - **PCA** is a linear map, so the user's embedding projects in *exactly*,
         *       through the same basis and the same unit-sphere normalisation the items
         *       went through. ``is_exact`` is true.
         *     - **UMAP** is non-parametric and has no transform for an unseen point. The
         *       star is placed at a softmax-weighted barycentre of the user's nearest
         *       projected items, which is an approximation. ``is_exact`` is false.
         *
         *     Collapsing the two into one unlabelled number would present an estimate
         *     with the same authority as a measurement.
         */
        get: operations["user_position_api_v1_embeddings_user__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest behavioural events
         * @description Accept events, advance the online feature state, invalidate caches.
         *
         *     Events are folded in through the same ``apply_event`` the offline scan
         *     uses, so online state evolves exactly as training would have evolved it.
         *     Unknown users are rejected rather than silently dropped, and the count is
         *     returned: a client sending ids the service cannot resolve should find out.
         */
        post: operations["ingest_events_api_v1_events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/insights/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Effective serving configuration
         * @description Expose the knobs that shape a recommendation.
         *
         *     Deliberately excludes every connection string and credential: this
         *     endpoint is reachable by the browser.
         */
        get: operations["config_insights_api_v1_insights_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/insights/dataset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dataset counts and provenance
         * @description Live counts from the loaded dataset, with provenance attached.
         *
         *     Provenance travels with the numbers deliberately: a consumer must be able
         *     to tell that behaviour is real Retailrocket while merchants, regions and
         *     prices are synthesised, without reading the docs.
         */
        get: operations["dataset_insights_api_v1_insights_dataset_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/insights/drift": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Feature drift between two windows
         * @description Serve the committed drift report.
         *
         *     Read from an artifact rather than computed per request: comparing two
         *     quarter-million-row windows takes seconds and allocates hundreds of
         *     megabytes, which is not something an interactive dashboard should trigger
         *     on every page load.
         */
        get: operations["drift_insights_api_v1_insights_drift_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/insights/evaluation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Offline model comparison
         * @description Return the committed model comparison.
         *
         *     Read from ``artifacts/evaluation/<preset>/results_test.json``, which is
         *     written by ``mercury train baselines``. If it is absent this returns 404
         *     with the command that produces it, rather than inventing plausible
         *     numbers to fill the dashboard.
         */
        get: operations["evaluation_insights_api_v1_insights_evaluation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/insights/experiment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Offline A/B simulation and gate verdict
         * @description Return the offline A/B comparison and the promotion gate result.
         *
         *     The payload carries is_simulated and a disclaimer describing exactly what
         *     the comparison establishes, so the frontend can render it behind a warning
         *     badge rather than as an online experiment result.
         */
        get: operations["experiment_insights_api_v1_insights_experiment_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/insights/metrics/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live latency and cache statistics
         * @description Summarise this process's own observed latency and cache behaviour.
         *
         *     Percentiles are computed from the Prometheus histogram buckets this
         *     process has actually recorded. **When no requests have been served the
         *     response says so** instead of reporting zeros that would read as
         *     measurements.
         */
        get: operations["metrics_summary_api_v1_insights_metrics_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/insights/ranking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Multi-stage pipeline results
         * @description Return the staged pipeline comparison and the retrieval ceiling.
         */
        get: operations["ranking_insights_api_v1_insights_ranking_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/insights/sample-users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Real user ids to explore with
         * @description Return a spread of real user ids, with how much history each one has.
         *
         *     Without this the explorer asks for a user id the visitor has no way to
         *     know, and the only reachable path through the product is the cold-start
         *     one. The ids are drawn across the history distribution rather than from
         *     its head, because a demo that only ever shows the most active user in the
         *     dataset is showing the easiest case and calling it typical.
         *
         *     Sorted deterministically, so a reload does not reshuffle the list.
         */
        get: operations["sample_users_api_v1_insights_sample_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items/{item_id}/similar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Items similar to a given item
         * @description Nearest neighbours by item-item collaborative similarity.
         */
        get: operations["similar_items_api_v1_items__item_id__similar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Loaded model versions
         * @description Report which models are loaded and which dataset produced them.
         */
        get: operations["models_status_api_v1_models_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recommendations/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Recommendations for a user
         * @description Return ranked, re-ranked recommendations for one user.
         *
         *     Context parameters are optional; supplying them changes the result, which
         *     is what makes contextual personalisation demonstrable rather than claimed.
         */
        get: operations["recommend_api_v1_recommendations__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recommendations/{user_id}/trace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stage-by-stage membership for one request
         * @description Return which items each stage held, for the pipeline and galaxy views.
         *
         *     Counts alone say 600 candidates became 10 recommendations. Only the
         *     membership says *which* 600, which is the difference between a diagram of
         *     a funnel and a picture of one that ran.
         */
        get: operations["recommend_trace_api_v1_recommendations__user_id__trace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/session/recommend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Session-context recommendations
         * @description Recommend from in-session behaviour.
         *
         *     ``user_id`` may be omitted: an anonymous session is served through the
         *     cold-start path rather than rejected, because an anonymous visitor is the
         *     most common request a live system receives.
         */
        post: operations["session_recommend_api_v1_session_recommend_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Report that the process is alive.
         *
         *     Deliberately checks nothing external.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Prometheus metrics
         * @description Expose metrics in the Prometheus text exposition format.
         */
        get: operations["metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Report whether this instance can serve, dependency by dependency.
         *
         *     Returns 503 when not ready so a load balancer removes the instance
         *     without needing to parse the body.
         */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * DataSource
         * @description Provenance of a dataset artifact.
         *
         *     Surfaced in the API and the frontend. The spec forbids presenting
         *     synthetic or augmented data as observed behaviour, so provenance is a
         *     first-class field rather than a documentation footnote.
         * @enum {string}
         */
        DataSource: "retailrocket" | "augmented" | "synthetic";
        /**
         * EventIngest
         * @description One behavioural event submitted to the API.
         *
         *     Accepted events advance the online feature state through the same
         *     ``apply_event`` the offline scan uses, so serving stays consistent with
         *     training rather than drifting between them.
         */
        EventIngest: {
            /**
             * Event Type
             * @description EventType value.
             */
            event_type: number;
            /** Item Id */
            item_id: number;
            /** Price */
            price?: number | null;
            /** Session Id */
            session_id?: string | null;
            /**
             * Timestamp
             * @description Defaults to server receive time.
             */
            timestamp?: string | null;
            /** User Id */
            user_id: string;
        };
        /** EventIngestResponse */
        EventIngestResponse: {
            /** Accepted */
            accepted: number;
            /**
             * Invalidated Cache Keys
             * @default 0
             */
            invalidated_cache_keys: number;
            /**
             * Rejected
             * @default 0
             */
            rejected: number;
            /** Rejection Reasons */
            rejection_reasons: {
                [key: string]: number;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Uptime Seconds */
            uptime_seconds: number;
            /** Version */
            version: string;
        };
        /**
         * ModelStatus
         * @description One loaded model's identity and provenance.
         */
        ModelStatus: {
            /** Dataset Hash */
            dataset_hash: string | null;
            /**
             * Is Loaded
             * @default true
             */
            is_loaded: boolean;
            /** Name */
            name: string;
            /** Params */
            params: {
                [key: string]: number | string | boolean | null;
            };
            /** Trained At */
            trained_at: string | null;
            /** Version */
            version: string;
        };
        /** ModelsStatusResponse */
        ModelsStatusResponse: {
            /** Dataset Hash */
            dataset_hash: string | null;
            /** Feature Schema Version */
            feature_schema_version: number;
            ranking: components["schemas"]["ModelStatus"] | null;
            /** Retrieval */
            retrieval: components["schemas"]["ModelStatus"][];
        };
        /**
         * PipelineTraceResponse
         * @description Which items each stage of the pipeline held, for one request.
         *
         *     A diagnostic, served from its own endpoint rather than bolted onto every
         *     recommendation response: it is two orders of magnitude larger than the
         *     result it explains, and the serving path has no use for it.
         *
         *     Requesting a trace forces a full pipeline run and bypasses the cache,
         *     because a cached response has no stage membership to report and
         *     reconstructing one from the final list would describe a funnel that never
         *     ran.
         */
        PipelineTraceResponse: {
            /**
             * Candidate Ids
             * @description Every item that survived retrieval and fusion.
             */
            candidate_ids: number[];
            /**
             * Candidate Sources
             * @description Item ids proposed by each source. An item appears under every source that returned it, so the overlap between sources is visible.
             */
            candidate_sources: {
                [key: string]: number[];
            };
            /** Filtered */
            filtered: {
                [key: string]: number;
            };
            /**
             * Final Ids
             * @description What the business rerank actually returned.
             */
            final_ids: number[];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /**
             * Is Cold Start
             * @default false
             */
            is_cold_start: boolean;
            latency: components["schemas"]["StageLatency"];
            /** Model Version */
            model_version: string;
            /**
             * N Candidates
             * @default 0
             */
            n_candidates: number;
            /**
             * Note
             * @default
             */
            note: string;
            /**
             * Ranked Ids
             * @description Candidates in ranker order, best first.
             */
            ranked_ids: number[];
            /**
             * Ranked Scores
             * @description Ranker output per entry in ranked_ids. An ordinal utility, not a probability.
             */
            ranked_scores: number[];
            /** Request Id */
            request_id: string;
            /** User Id */
            user_id: string;
        };
        /** ReadinessCheck */
        ReadinessCheck: {
            /** Detail */
            detail: string | null;
            /** Name */
            name: string;
            /** Ready */
            ready: boolean;
        };
        /**
         * ReadinessResponse
         * @description Readiness, with per-dependency detail.
         *
         *     A bare boolean is not actionable during an incident: what matters is
         *     *which* dependency is down, so each is reported separately.
         */
        ReadinessResponse: {
            /** Checks */
            checks: components["schemas"]["ReadinessCheck"][];
            /** Ready */
            ready: boolean;
        };
        /**
         * Recommendation
         * @description One recommended item.
         */
        Recommendation: {
            /**
             * Adjustments
             * @description Per-rule breakdown of business_adjustment.
             */
            adjustments: {
                [key: string]: number;
            };
            /**
             * Business Adjustment
             * @description Sum of deterministic policy adjustments. Kept separate from the model score so any ranking change is attributable.
             * @default 0
             */
            business_adjustment: number;
            /** Category Id */
            category_id: number | null;
            /**
             * Final Score
             * @description ml_relevance_score + business_adjustment
             */
            final_score: number;
            /** Item Id */
            item_id: number;
            /** Merchant Id */
            merchant_id: number | null;
            /**
             * Ml Relevance Score
             * @description The ranking model's output. An ordinal utility from LambdaRank, NOT a calibrated probability - do not read it as one.
             */
            ml_relevance_score: number;
            /** Price */
            price: number | null;
            /**
             * Rank
             * @description 1-based position in the list
             */
            rank: number;
            /**
             * Sources
             * @description Retrieval sources that proposed this item.
             */
            sources: string[];
            /** Vertical */
            vertical: number | null;
        };
        /**
         * RecommendationExplanation
         * @description Why one item was ranked where it was.
         *
         *     Values are exact TreeSHAP contributions from the ranking model, signed:
         *     negative means the feature pushed this item *down*. They are the model's
         *     real attributions for this specific score, not a narrative written after
         *     the fact.
         */
        RecommendationExplanation: {
            /** Contributions */
            contributions: {
                [key: string]: number;
            };
            /** Item Id */
            item_id: number;
        };
        /**
         * RecommendationResponse
         * @description The response returned by the recommendation endpoints.
         */
        RecommendationResponse: {
            /**
             * Cache Hit
             * @default false
             */
            cache_hit: boolean;
            /**
             * Candidate Sources
             * @description Candidate count contributed per source.
             */
            candidate_sources: {
                [key: string]: number;
            };
            /**
             * @description Provenance of the underlying dataset. Behaviour is real Retailrocket; merchants, regions, prices and verticals are synthesised. See docs/data-card.md.
             * @default augmented
             */
            data_provenance: components["schemas"]["DataSource"];
            /** Explanations */
            explanations: components["schemas"]["RecommendationExplanation"][];
            /**
             * Filtered
             * @description Items removed by hard filters, per reason. Surfaced because silent filtering degrades results with no visible cause.
             */
            filtered: {
                [key: string]: number;
            };
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /**
             * Is Cold Start
             * @description True when the user had no usable history and the cold-start path served this.
             * @default false
             */
            is_cold_start: boolean;
            latency: components["schemas"]["StageLatency"];
            /** Model Version */
            model_version: string;
            /**
             * N Candidates
             * @description Candidates that reached the ranking stage.
             * @default 0
             */
            n_candidates: number;
            /** Recommendations */
            recommendations: components["schemas"]["Recommendation"][];
            /** Request Id */
            request_id: string;
            /** User Id */
            user_id: string;
        };
        /**
         * RequestContext
         * @description Context a caller may supply to shape the recommendation.
         */
        RequestContext: {
            /** Device */
            device?: number | null;
            /** Hour */
            hour?: number | null;
            /** Region Id */
            region_id?: number | null;
            /**
             * Session Items
             * @description Items seen this session.
             */
            session_items?: number[];
            /** Vertical */
            vertical?: number | null;
            /** Weekday */
            weekday?: number | null;
        };
        /**
         * SessionRecommendRequest
         * @description Body for session-based recommendation.
         */
        SessionRecommendRequest: {
            /**
             * @default {
             *       "session_items": []
             *     }
             */
            context: components["schemas"]["RequestContext"];
            /**
             * K
             * @default 10
             */
            k: number;
            /** Session Items */
            session_items?: number[];
            /**
             * User Id
             * @description Omit for an anonymous session; cold-start serves it.
             */
            user_id?: string | null;
        };
        /** SimilarItemsResponse */
        SimilarItemsResponse: {
            /** Item Id */
            item_id: number;
            /** Latency Ms */
            latency_ms: number;
            /** Model Version */
            model_version: string;
            /** Similar */
            similar: components["schemas"]["Recommendation"][];
        };
        /**
         * StageLatency
         * @description Milliseconds spent in each stage of the request.
         *
         *     Returned on every response so a slow request is diagnosable from the
         *     response alone. The fields mirror the pipeline stages exactly, which is
         *     what lets the frontend's Pipeline Inspector show real numbers rather than
         *     a drawing.
         */
        StageLatency: {
            /**
             * Cache Lookup Ms
             * @default 0
             */
            cache_lookup_ms: number;
            /**
             * Candidate Generation Ms
             * @default 0
             */
            candidate_generation_ms: number;
            /**
             * Feature Lookup Ms
             * @default 0
             */
            feature_lookup_ms: number;
            /**
             * Ranking Ms
             * @default 0
             */
            ranking_ms: number;
            /**
             * Reranking Ms
             * @default 0
             */
            reranking_ms: number;
            /**
             * Total Ms
             * @default 0
             */
            total_ms: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    projection_api_v1_embeddings_projection_get: {
        parameters: {
            query?: {
                method?: string;
                max_items?: number;
                vertical?: number | null;
                preset?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    projection_meta_api_v1_embeddings_projection_meta_get: {
        parameters: {
            query?: {
                preset?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    user_position_api_v1_embeddings_user__user_id__get: {
        parameters: {
            query?: {
                method?: string;
                preset?: string;
            };
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_events_api_v1_events_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventIngest"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventIngestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    config_insights_api_v1_insights_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    dataset_insights_api_v1_insights_dataset_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    drift_insights_api_v1_insights_drift_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    evaluation_insights_api_v1_insights_evaluation_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    experiment_insights_api_v1_insights_experiment_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    metrics_summary_api_v1_insights_metrics_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    ranking_insights_api_v1_insights_ranking_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    sample_users_api_v1_insights_sample_users_get: {
        parameters: {
            query?: {
                n?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    similar_items_api_v1_items__item_id__similar_get: {
        parameters: {
            query?: {
                k?: number;
            };
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimilarItemsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    models_status_api_v1_models_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelsStatusResponse"];
                };
            };
        };
    };
    recommend_api_v1_recommendations__user_id__get: {
        parameters: {
            query?: {
                k?: number;
                hour?: number | null;
                weekday?: number | null;
                region_id?: number | null;
                vertical?: number | null;
                /** @description Bypass the cache. */
                no_cache?: boolean;
                /** @description Evaluate as of this instant (demo environments only). */
                as_of?: string | null;
            };
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recommend_trace_api_v1_recommendations__user_id__trace_get: {
        parameters: {
            query?: {
                k?: number;
                hour?: number | null;
                weekday?: number | null;
                region_id?: number | null;
                vertical?: number | null;
            };
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineTraceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    session_recommend_api_v1_session_recommend_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionRecommendRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
}
