"""initial schema

Revision ID: 9f09e0cb036c
Revises:
Create Date: 2026-09-20 17:48:25.290100

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9f09e0cb036c"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "experiments",
        sa.Column("experiment_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("control_model_version", sa.String(length=128), nullable=False),
        sa.Column("treatment_model_version", sa.String(length=128), nullable=False),
        sa.Column("traffic_split", sa.Float(), nullable=False),
        sa.Column("is_simulated", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.CheckConstraint(
            "traffic_split > 0 AND traffic_split < 1", name="ck_experiment_split_range"
        ),
        sa.PrimaryKeyConstraint("experiment_id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "interactions",
        sa.Column("event_id", sa.BigInteger(), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.BigInteger(), nullable=True),
        sa.Column("event_type", sa.SmallInteger(), nullable=False),
        sa.Column("merchant_id", sa.Integer(), nullable=True),
        sa.Column("vertical", sa.SmallInteger(), nullable=True),
        sa.Column("region_id", sa.SmallInteger(), nullable=True),
        sa.Column("device", sa.SmallInteger(), nullable=True),
        sa.Column("price_at_event", sa.Float(), nullable=True),
        sa.Column("is_repeat", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_index("ix_interactions_item_ts", "interactions", ["item_id", "ts"], unique=False)
    op.create_index("ix_interactions_ts", "interactions", ["ts"], unique=False)
    op.create_index("ix_interactions_user_ts", "interactions", ["user_id", "ts"], unique=False)
    op.create_table(
        "merchants",
        sa.Column("merchant_id", sa.Integer(), nullable=False),
        sa.Column("vertical", sa.SmallInteger(), nullable=False),
        sa.Column("region_id", sa.SmallInteger(), nullable=False),
        sa.Column("rating", sa.Float(), nullable=False),
        sa.Column("delivery_radius_km", sa.Float(), nullable=False),
        sa.Column("avg_delivery_minutes", sa.SmallInteger(), nullable=False),
        sa.CheckConstraint("rating >= 0 AND rating <= 5", name="ck_merchant_rating_range"),
        sa.PrimaryKeyConstraint("merchant_id"),
    )
    op.create_index(
        "ix_merchants_region_vertical", "merchants", ["region_id", "vertical"], unique=False
    )
    op.create_table(
        "model_metadata",
        sa.Column("model_version", sa.String(length=128), nullable=False),
        sa.Column("model_type", sa.String(length=64), nullable=False),
        sa.Column("trained_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("dataset_hash", sa.String(length=64), nullable=True),
        sa.Column("feature_schema_version", sa.SmallInteger(), nullable=False),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("artifact_uri", sa.Text(), nullable=True),
        sa.Column("mlflow_run_id", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("promoted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('candidate', 'staging', 'production', 'archived')", name="ck_model_status"
        ),
        sa.PrimaryKeyConstraint("model_version"),
    )
    op.create_index(
        "ix_model_metadata_type_trained",
        "model_metadata",
        ["model_type", "trained_at"],
        unique=False,
    )
    op.create_index(
        "uq_one_production_model_per_type",
        "model_metadata",
        ["model_type"],
        unique=True,
        postgresql_where=sa.text("status = 'production'"),
    )
    op.create_table(
        "recommendation_requests",
        sa.Column("request_id", sa.String(length=36), nullable=False),
        sa.Column(
            "ts", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("external_user_id", sa.String(length=64), nullable=True),
        sa.Column("k", sa.SmallInteger(), nullable=False),
        sa.Column("model_version", sa.String(length=128), nullable=False),
        sa.Column("feature_schema_version", sa.SmallInteger(), nullable=False),
        sa.Column("context", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("cache_hit", sa.Boolean(), nullable=False),
        sa.Column("is_cold_start", sa.Boolean(), nullable=False),
        sa.Column("n_candidates", sa.Integer(), nullable=False),
        sa.Column("cache_ms", sa.Float(), nullable=True),
        sa.Column("feature_ms", sa.Float(), nullable=True),
        sa.Column("retrieval_ms", sa.Float(), nullable=True),
        sa.Column("ranking_ms", sa.Float(), nullable=True),
        sa.Column("rerank_ms", sa.Float(), nullable=True),
        sa.Column("total_ms", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("request_id"),
    )
    op.create_index(
        "ix_rec_requests_context",
        "recommendation_requests",
        ["context"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "ix_rec_requests_model_ts", "recommendation_requests", ["model_version", "ts"], unique=False
    )
    op.create_index(
        "ix_rec_requests_user_ts", "recommendation_requests", ["user_id", "ts"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("source_user_id", sa.BigInteger(), nullable=False),
        sa.Column("region_id", sa.SmallInteger(), nullable=False),
        sa.Column("signup_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("device_pref", sa.SmallInteger(), nullable=False),
        sa.Column("is_cold", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("source_user_id"),
    )
    op.create_index("ix_users_region", "users", ["region_id"], unique=False)
    op.create_table(
        "experiment_results",
        sa.Column("experiment_id", sa.String(length=36), nullable=False),
        sa.Column("metric", sa.String(length=64), nullable=False),
        sa.Column("variant", sa.String(length=32), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("lower_ci", sa.Float(), nullable=True),
        sa.Column("upper_ci", sa.Float(), nullable=True),
        sa.Column("n", sa.BigInteger(), nullable=False),
        sa.Column("p_value", sa.Float(), nullable=True),
        sa.Column(
            "computed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["experiment_id"], ["experiments.experiment_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("experiment_id", "metric", "variant"),
        sa.UniqueConstraint(
            "experiment_id", "metric", "variant", name="uq_experiment_metric_variant"
        ),
    )
    op.create_table(
        "items",
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("source_item_id", sa.BigInteger(), nullable=False),
        sa.Column("merchant_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("vertical", sa.SmallInteger(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("base_rating", sa.Float(), nullable=True),
        sa.Column("available_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("available_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_cold", sa.Boolean(), nullable=False),
        sa.CheckConstraint("price > 0", name="ck_item_price_positive"),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.merchant_id"],
        ),
        sa.PrimaryKeyConstraint("item_id"),
        sa.UniqueConstraint("source_item_id"),
    )
    op.create_index("ix_items_category", "items", ["category_id"], unique=False)
    op.create_index(
        "ix_items_currently_listed",
        "items",
        ["item_id"],
        unique=False,
        postgresql_where=sa.text("available_until IS NULL"),
    )
    op.create_index(
        "ix_items_vertical_category", "items", ["vertical", "category_id"], unique=False
    )
    op.create_table(
        "recommendation_results",
        sa.Column("request_id", sa.String(length=36), nullable=False),
        sa.Column("rank", sa.SmallInteger(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("ml_score", sa.Float(), nullable=False),
        sa.Column("business_delta", sa.Float(), nullable=False),
        sa.Column("final_score", sa.Float(), nullable=False),
        sa.Column("sources", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["request_id"], ["recommendation_requests.request_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("request_id", "rank"),
    )
    op.create_index("ix_rec_results_item", "recommendation_results", ["item_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_rec_results_item", table_name="recommendation_results")
    op.drop_table("recommendation_results")
    op.drop_index("ix_items_vertical_category", table_name="items")
    op.drop_index(
        "ix_items_currently_listed",
        table_name="items",
        postgresql_where=sa.text("available_until IS NULL"),
    )
    op.drop_index("ix_items_category", table_name="items")
    op.drop_table("items")
    op.drop_table("experiment_results")
    op.drop_index("ix_users_region", table_name="users")
    op.drop_table("users")
    op.drop_index("ix_rec_requests_user_ts", table_name="recommendation_requests")
    op.drop_index("ix_rec_requests_model_ts", table_name="recommendation_requests")
    op.drop_index(
        "ix_rec_requests_context", table_name="recommendation_requests", postgresql_using="gin"
    )
    op.drop_table("recommendation_requests")
    op.drop_index(
        "uq_one_production_model_per_type",
        table_name="model_metadata",
        postgresql_where=sa.text("status = 'production'"),
    )
    op.drop_index("ix_model_metadata_type_trained", table_name="model_metadata")
    op.drop_table("model_metadata")
    op.drop_index("ix_merchants_region_vertical", table_name="merchants")
    op.drop_table("merchants")
    op.drop_index("ix_interactions_user_ts", table_name="interactions")
    op.drop_index("ix_interactions_ts", table_name="interactions")
    op.drop_index("ix_interactions_item_ts", table_name="interactions")
    op.drop_table("interactions")
    op.drop_table("experiments")
    # ### end Alembic commands ###
