"""Closed vocabularies shared by the data, model, serving and frontend layers.

Every enum here is stored on disk as its integer ``value`` (compact in parquet
and Postgres) but is always constructed through the enum, never through a bare
literal. ``IntEnum`` is used so the values serialise directly into numpy and
Postgres ``smallint`` columns without a conversion layer.

Changing an existing value is a breaking change to persisted data and to the
feature-schema hash. Append new members; never renumber.
"""

from __future__ import annotations

from enum import IntEnum, StrEnum


class EventType(IntEnum):
    """Behavioural event types, ordered by increasing intent.

    The ordering is meaningful: ``item_cf`` and the implicit-feedback models
    weight events by configured confidence values that rise monotonically with
    this ordinal. Weights live in ``configs/`` and are justified in
    ``docs/recommender-system.md`` — they are never hard-coded.
    """

    IMPRESSION = 0
    SKIP = 1
    CLICK = 2
    VIEW = 3
    SEARCH = 4
    WISHLIST = 5
    ADD_TO_CART = 6
    REMOVE_FROM_CART = 7
    RATING = 8
    PURCHASE = 9
    REPEAT_PURCHASE = 10

    @property
    def is_conversion(self) -> bool:
        """Whether this event counts as a conversion for CTR/CVR metrics."""
        return self in {EventType.PURCHASE, EventType.REPEAT_PURCHASE}

    @property
    def is_negative_signal(self) -> bool:
        """Whether this event indicates disinterest rather than engagement."""
        return self in {EventType.SKIP, EventType.REMOVE_FROM_CART}


class Vertical(IntEnum):
    """Commerce verticals of the multi-vertical on-demand platform."""

    FOOD_DELIVERY = 0
    RESTAURANT = 1
    GROCERY = 2
    PHARMACY = 3
    COMMERCE = 4
    LIFESTYLE = 5

    @property
    def is_perishable(self) -> bool:
        """Perishable verticals carry tight availability windows."""
        return self in {Vertical.FOOD_DELIVERY, Vertical.RESTAURANT, Vertical.GROCERY}


class Device(IntEnum):
    """Originating device class for a session."""

    MOBILE_APP = 0
    MOBILE_WEB = 1
    DESKTOP_WEB = 2
    TABLET = 3


class Cohort(StrEnum):
    """Population cohorts used for sliced evaluation.

    Cold-start behaviour is a stated requirement, so cold users and items are
    assigned deliberately at generation time rather than discovered after the
    fact. Evaluation reports metrics per cohort, because a headline number
    averaged over warm and cold users hides exactly the behaviour that matters.
    """

    WARM = "warm"
    COLD_USER = "cold_user"
    COLD_ITEM = "cold_item"
    RETURNING = "returning"


class RetrievalSource(StrEnum):
    """Which candidate generator proposed an item.

    Carried through fusion into the API response and the Pipeline Inspector so
    a candidate's provenance stays visible end to end.
    """

    POPULARITY = "popularity"
    ITEM_CF = "item_cf"
    MATRIX_FACTORIZATION = "matrix_factorization"
    TWO_TOWER = "two_tower"
    COLD_START = "cold_start"
    RECENT_SESSION = "recent_session"


class ModelStatus(StrEnum):
    """Lifecycle state of a registered model version."""

    CANDIDATE = "candidate"
    STAGING = "staging"
    PRODUCTION = "production"
    ARCHIVED = "archived"


class DataSource(StrEnum):
    """Provenance of a dataset artifact.

    Surfaced in the API and the frontend. The spec forbids presenting
    synthetic or augmented data as observed behaviour, so provenance is a
    first-class field rather than a documentation footnote.
    """

    RETAILROCKET = "retailrocket"
    """Real observed events from the Retailrocket dataset (CC BY-NC-SA 4.0)."""

    AUGMENTED = "augmented"
    """Real events enriched with synthesised attributes (merchant, region, price)."""

    SYNTHETIC = "synthetic"
    """Fully generated by the seeded behavioural simulator."""


__all__ = [
    "Cohort",
    "DataSource",
    "Device",
    "EventType",
    "ModelStatus",
    "RetrievalSource",
    "Vertical",
]
